## Generar PIN
POST http://localhost:3000/api/generar-pin HTTP/1.1
content-type: application/json

{
    "nombre": "Jairo Barrera",
    "correo": "jairoBarrera@gmail.com"
}

### Verificar PIN
POST http://localhost:3000/api/verificar-pin HTTP/1.1
content-type: application/json

{
    "pin": "46108"
}

### Generar PIN PROD
POST https://registroasistenciaconpin-production.up.railway.app/api/generar-pin HTTP/1.1
content-type: application/json

{
    "nombre": "Jairo Barrera prod1",
    "correo": "jairoBarreraPROD1@gmail.com"
}

### Verificar PIN prod
POST https://registroasistenciaconpin-production.up.railway.app/api/verificar-pin HTTP/1.1
content-type: application/json

{
    "pin": "60723"
}