## Generar PIN
POST https://registroasistenciaconpin-production.up.railway.app/api/generar-pin HTTP/1.1
content-type: application/json

{
    "nombre": "Jairo Barrera",
    "correo": "jairoBarrera@gmail.com"
}

### Verificar PIN
POST http://192.168.81.245:3000/api/verificar-pin HTTP/1.1
content-type: application/json

{
    "pin": "26373"
}